name: Docker

on:
  push:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    container: openjdk:8-jdk
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:latest
        
        # Provide the password for postgres
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: tp_devops
          POSTGRES_DB: tp_devops
          POSTGRES_USER: tp_devops

    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew assemble
      - run: ./gradlew check -Pdatabase.url=postgres:5432/tp_devops
      - run: docker build /docker/ -t matthewhaas/tp-devops
      - run: docker push matthewhaas/tp-devops

  
