name: Docker

on:
  push:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew assemble
      - run: docker-compose up
      - run: ./gradlew check

  
